# Generated by Django 4.2.1 on 2023-05-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('gpa', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
